hostname: KT_3

interfaces:
  config:
    - name: Loopback0
      description: KT_3_Loopback
      enabled: true
    - name: Ethernet0/0
      description: TO_KT_2
      enabled: true
    - name: Ethernet0/1
      description: TO_KT_6
      enabled: true
    - name: Ethernet0/2
      description: TO_KT_1
      enabled: true
    - name: Ethernet0/3
      description: TO_KT_5
      enabled: true
    - name: Serial3/0
      description: TO_LG_2
      enabled: true
    # unused ports
    - name: Ethernet2/0
      enabled: false
    - name: Ethernet2/1
      enabled: false
    - name: Ethernet2/2
      enabled: false
    - name: Ethernet2/3
      enabled: false

l3_interfaces:
  config:
    - name: Loopback0
      ipv4:
        - address: 121.160.0.3/32
    - name: Ethernet0/0
      ipv4:
        - address: 121.160.42.10/30
    - name: Ethernet0/1
      ipv4:
        - address: 121.160.42.33/30
    - name: Ethernet0/2
      ipv4:
        - address: 121.160.42.6/30
    - name: Ethernet0/3
      ipv4:
        - address: 121.160.42.69/30
    - name: Serial3/0
      ipv4:
        - address: 61.250.1.253/30

ospf_interfaces:
  config:
    - name: Ethernet0/0
      address_family:
        - afi: ipv4
          network:
            point_to_point: true
    - name: Ethernet0/1
      address_family:
        - afi: ipv4
          network:
            point_to_point: true
    - name: Ethernet0/2
      address_family:
        - afi: ipv4
          network:
            point_to_point: true
    - name: Ethernet0/3
      address_family:
        - afi: ipv4
          network:
            point_to_point: true

ospfv2:
  config:
    processes:
      - process_id: 1
        prefix_suppression: true
        network:
          - address: 121.160.0.3
            wildcard_bits: 0.0.0.0
            area: "0"
          - address: 121.160.42.0
            wildcard_bits: 0.0.0.255
            area: "0"

bgp_global:
  config:
    as_number: "{{ bgp_as }}"
    bgp:
      log_neighbor_changes: true
    neighbors:
      - neighbor_address: 61.250.1.254
        remote_as: "1112"
      - neighbor_address: 121.160.0.6
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        next_hop_self:
          set: true
