hostname: KT_6

interfaces:
  config:
    - name: Loopback0
      description: KT_6_Loopback_RR
      enabled: true
    - name: Ethernet0/1
      description: TO_KT_3
      enabled: true
    - name: Ethernet0/2
      description: TO_KT_2
      enabled: true
    # unused ports
    - name: Ethernet2/0
      enabled: false
    - name: Ethernet2/1
      enabled: false
    - name: Ethernet2/2
      enabled: false
    - name: Ethernet2/3
      enabled: false

l3_interfaces:
  config:
    - name: Loopback0
      ipv4:
        - address: 121.160.0.6/32
    - name: Ethernet0/1
      ipv4:
        - address: 121.160.42.34/30
    - name: Ethernet0/2
      ipv4:
        - address: 121.160.42.30/30

ospf_interfaces:
  config:
    - name: Ethernet0/1
      address_family:
        - afi: ipv4
          network:
            point_to_point: true
    - name: Ethernet0/2
      address_family:
        - afi: ipv4
          network:
            point_to_point: true

ospfv2:
  config:
    processes:
      - process_id: 1
        prefix_suppression: true
        network:
          - address: 121.160.0.6
            wildcard_bits: 0.0.0.0
            area: "0"
          - address: 121.160.42.0
            wildcard_bits: 0.0.0.255
            area: "0"

bgp_global:
  config:
    as_number: "{{ bgp_as }}"
    bgp:
      log_neighbor_changes: true
    neighbors:
      - neighbor_address: 121.160.0.1
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        route_reflector_client: true
      - neighbor_address: 121.160.0.2
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        route_reflector_client: true
      - neighbor_address: 121.160.0.3
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        route_reflector_client: true
      - neighbor_address: 121.160.0.4
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        route_reflector_client: true
      - neighbor_address: 121.160.0.5
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        route_reflector_client: true
