hostname: R1

interfaces:
  config:
    - name: Ethernet0/0
      description: TO_R2
      enabled: true
    - name: Ethernet1/0
      description: TO_R3
      enabled: true
    - name: Ethernet2/0
      description: TO_R5
      enabled: true
    - name: Loopback0
      description: R1_Loopback
      enabled: true
    # unused ports
    - name: Ethernet0/1
      enabled: false
    - name: Ethernet0/2
      enabled: false
    - name: Ethernet0/3
      enabled: false
    - name: Ethernet1/1
      enabled: false
    - name: Ethernet1/2
      enabled: false
    - name: Ethernet1/3
      enabled: false
    - name: Ethernet2/1
      enabled: false
    - name: Ethernet2/2
      enabled: false
    - name: Ethernet2/3
      enabled: false

l3_interfaces:
  config:
    - name: Ethernet0/0
      ipv4:
        - address: 123.45.67.1/30
    - name: Ethernet1/0
      ipv4:
        - address: 123.45.67.5/30
    - name: Ethernet2/0
      ipv4:
        - address: 123.45.67.17/30
    - name: Loopback0
      ipv4:
        - address: 123.45.0.1/32

ospf_interfaces:
  config:
    - name: Ethernet0/0
      address_family:
        - afi: ipv4
          network:
            point_to_point: true
    - name: Ethernet1/0
      address_family:
        - afi: ipv4
          network:
            point_to_point: true
    - name: Ethernet2/0
      address_family:
        - afi: ipv4
          network:
            point_to_point: true

ospfv2:
  config:
    processes:
      - process_id: 1
        prefix_suppression: true
        network:
          - address: 123.45.0.1
            wildcard_bits: 0.0.0.0
            area: "0"
          - address: 123.45.67.0
            wildcard_bits: 0.0.0.255
            area: "0"

bgp_global:
  config:
    as_number: "{{ bgp_as }}"
    bgp:
      log_neighbor_changes: true
    neighbors:
      - neighbor_address: 123.45.0.2
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
      - neighbor_address: 123.45.0.3
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        route_reflector_client: true
      - neighbor_address: 123.45.0.5
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        route_reflector_client: true
      - neighbor_address: 123.45.0.7
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        route_reflector_client: true
      - neighbor_address: 123.45.0.8
        remote_as: "{{ bgp_as }}"
        update_source: Loopback0
        route_reflector_client: true
