---
# R3 — AT&T PE (Provider Edge), RR Client / Area 0-1 ABR
interfaces:
  - { name: Loopback0,   ipv4: 123.45.0.3,   mask: 255.255.255.255, description: "Router-ID" }
  - { name: Ethernet0/0, ipv4: 123.45.67.6,  mask: 255.255.255.252, ospf_network: point-to-point }
  - { name: Ethernet1/0, ipv4: 123.45.68.37, mask: 255.255.255.252, ospf_network: point-to-point }

ospf_networks:
  - { prefix: 123.45.0.3,  wildcard: 0.0.0.0,   area: 1 }
  - { prefix: 123.45.67.0, wildcard: 0.0.0.255, area: 0 }
  - { prefix: 123.45.68.0, wildcard: 0.0.0.255, area: 1 }

bgp_neighbors:
  - { ip: 123.45.0.1, remote_as: 123, update_source: Loopback0, description: "iBGP to R1 (RR)" }
